version: '3'
volumes:
  storage:

services:
  storage:
    image: "minio/minio"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    command: server /data
  node:
    image: "mynode:latest"
    user: node
    working_dir: /home/node
    volumes:
      - .:/home/node
    ports:
      - "8888:3000"
    command: npm start